setups_defaults = {'minimal':
                   {'K':  '_pv',
                    'Ca': '_pv',
                    'Rb': '_pv',
                    'Sr': '_sv',
                    'Y':  '_sv',
                    'Zr': '_sv',
                    'Nb': '_pv',
                    'Cs': '_sv',
                    'Ba': '_sv',
                    'Fr': '_sv',
                    'Ra': '_sv',
                    'Sc': '_sv'},
                    #
                   'recommended':
                    {'Li': '_sv',
                     'Na': '_pv',
                     'K': '_sv',
                     'Ca': '_sv',
                     'Sc': '_sv',
                     'Ti': '_sv',
                     'V': '_sv',
                     'Cr': '_pv',
                     'Mn': '_pv',
                     'Ga': '_d',
                     'Ge': '_d',
                     'Rb': '_sv',
                     'Sr': '_sv',
                     'Y': '_sv',
                     'Zr': '_sv',
                     'Nb': '_sv',
                     'Mo': '_sv',
                     'Tc': '_pv',
                     'Ru': '_pv',
                     'Rh': '_pv',
                     'In': '_d',
                     'Sn': '_d',
                     'Cs': '_sv',
                     'Ba': '_sv',
                     'Pr': '_3',
                     'Nd': '_3',
                     'Pm': '_3',
                     'Sm': '_3',
                     'Eu': '_2',
                     'Gd': '_3',
                     'Tb': '_3',
                     'Dy': '_3',
                     'Ho': '_3',
                     'Er':'_3',
                     'Tm':'_3',
                     'Yb':'_2',
                     'Lu':'_3',
                     'Hf': '_pv',
                     'Ta': '_pv',
                     'W': '_pv',
                     'Tl': '_d',
                     'Pb': '_d',
                     'Bi':'_d',
                     'Po': '_d',
                     'At': '_d',
                     'Fr':'_sv',
                     'Ra':'_sv'}}
